<?php

declare(strict_types=1);

/**
 * UZ Estates current listings.
 * Almaris Villas is off-plan; the rest are land plots.
 */
return [
    [
        'title'             => '12 Perch The Vale',
        'property_type'     => 'Plot',
        'listing_purpose'   => 'Sale',
        'status'            => 'Available',
        'price'             => 'Rs 6,000,000',
        'price_note'        => 'Negotiable',
        'size'              => '12 Perch · 506 m²',
        'location_name'     => 'The Vale',
        'location_area'     => 'The Vale',
        'short_description' => 'Residential plot on the Royal Road in The Vale with construction permits and utilities in place.',
        'full_description'  => "This residential plot sits in The Vale, at the junction of La Salette Road and Sottise Road along the Royal Road corridor. It offers a central north coast address with strong everyday convenience.\n\nThe land measures 12 perches, equivalent to 506 square metres, and is suited to a private home build. Construction permits are in place, and both water and electricity are available on site.\n\nThe plot is priced at Rs 6,000,000 and is negotiable. It will appeal to buyers who want a practical, ready to build site in a well connected part of the north.",
        'is_featured'       => 1,
        'show_on_home'      => 1,
        'latitude'          => '-20.0280399',
        'longitude'         => '57.600975',
        'google_maps_link'  => 'https://maps.app.goo.gl/jmSEFbHArHb6xske7',
        'features'          => [
            'Land size'              => '12 perches (506 m²)',
            'Price'                  => 'Rs 6,000,000 (negotiable)',
            'Plus code'              => 'XJC2+Q9Q The Vale',
            'Road frontage'          => 'Royal Road position',
            'Construction permits'   => 'Available',
            'Water & electricity'    => 'Available',
            'Address reference'      => 'La Salette Rd & Sottise Rd, Vale',
        ],
    ],
    [
        'title'             => 'Almaris Villas',
        'property_type'     => 'Villa',
        'listing_purpose'   => 'Sale',
        'status'            => 'Off-Plan',
        'price'             => 'Rs 9,700,000',
        'price_note'        => 'From',
        'size'              => '1,250 sq ft · 7 to 8.8 Perch',
        'location_name'     => 'Grand Baie',
        'location_area'     => 'Grand Baie',
        'short_description' => 'Modern off-plan villa for sale in Grand Baie, behind Super U and minutes from the beach. Two lots available from Rs 9.7M, land included.',
        'full_description'  => "Seize this exceptional opportunity to acquire a modern off-plan villa in one of Grand Baie's most sought-after areas, ideally located behind Super U and just minutes from Grand Baie public beach.\n\nTwo villa units remain available, each sold with land included. Every unit offers 1,250 sq ft of living space, 3 bedrooms, a private pool, and premium finishes, ideal as a primary residence, holiday home, or rental investment.\n\nSelect a unit below to view photos, room details, pricing, and plans for each lot.",
        'is_featured'       => 1,
        'show_on_home'      => 1,
        'latitude'          => '-20.0080757',
        'longitude'         => '57.5895538',
        'google_maps_link'  => 'https://maps.app.goo.gl/EaaWG4mMBQ27uz96A',
        'lots'              => [
            [
                'label'       => 'Lot 1',
                'size'        => '7 Perch',
                'price'       => 'Rs 9,700,000',
                'description' => "Modern off-plan villa with land included on a 7-perch plot.\n\nVilla floor area: 1,250 sq ft\n\nThis unit matches the premium specification of Lot 2, with 3 bedrooms, a semi-equipped kitchen, a private pool, a carport, and high-quality finishes throughout.\n\nLand included. Semi-furnished.",
                'bedrooms'    => '3',
                'bathrooms'   => '2',
                'villa_size'  => '1,250 sq ft',
                'status'      => 'Available',
            ],
            [
                'label'       => 'Lot 2',
                'size'        => '8.8 Perch',
                'price'       => 'Rs 10,700,000',
                'description' => "Modern off-plan villa with land included.\n\nVilla floor area: 1,250 sq ft\n\nVilla features\n• 3 bedrooms, including 1 master en suite and 2 with a shared bathroom\n• Fitted, semi-equipped kitchen\n• Tiling throughout, aluminium doors and windows\n• Electrical and plumbing included\n\nOutdoor amenities\n• Private swimming pool with pump\n• Pergola carport and parking for 2 vehicles\n• Garden and outdoor spaces\n\nLand included. Semi-furnished. Ideal as a primary residence, holiday home, or rental investment.",
                'bedrooms'    => '3',
                'bathrooms'   => '2',
                'villa_size'  => '1,250 sq ft',
                'status'      => 'Available',
            ],
        ],
        'features'          => [
            'Sale format'            => 'Off-plan villa',
            'Villa size'             => '1,250 sq ft',
            'Bedrooms'               => '3 (1 master en suite, 2 with shared bathroom)',
            'Kitchen'                => 'Fitted, semi-equipped',
            'Finishes'               => 'Tiling throughout, aluminium doors and windows',
            'Utilities'              => 'Electrical and plumbing included',
            'Outdoor'                => 'Private pool with pump, pergola carport, parking for 2',
            'Land included'          => 'Yes',
            'Furnishing'             => 'Semi-furnished',
            'Plus code'              => 'XHRQ+QR7 Grand Baie',
            'Available lots'         => 'Lot 1 (7 perches) · Lot 2 (8.8 perches)',
            'Access'                 => 'Chemin Vingt Pieds · Grand Baie public beach',
            'Position'               => 'Behind Super U Grand Baie',
        ],
    ],
    [
        'title'             => '1 Arpent Grand Baie',
        'property_type'     => 'Plot',
        'listing_purpose'   => 'Sale',
        'status'            => 'Available',
        'price'             => 'Rs 40,000,000',
        'price_note'        => null,
        'size'              => '1 Arpent',
        'location_name'     => 'Grand Baie',
        'location_area'     => 'Grand Baie',
        'short_description' => 'Full arpent residential plot in Grand Baie, located behind Super U.',
        'full_description'  => "This is a one arpent residential plot in Grand Baie, set behind Super U in a well established and highly sought after part of the north coast.\n\nAt this scale, the land offers genuine scope for a substantial private residence, a carefully planned small development, or a long term hold in one of Mauritius's strongest coastal markets. The setting combines village convenience with the appeal of a prime Grand Baie address.\n\nFurther details on access, boundaries, and the surrounding context can be provided on enquiry.",
        'is_featured'       => 1,
        'show_on_home'      => 1,
        'latitude'          => '-20.0095615',
        'longitude'         => '57.5879974',
        'google_maps_link'  => 'https://maps.app.goo.gl/NdSArLxdVArZsXte6',
        'features'          => [
            'Land size'              => '1 arpent',
            'Price'                  => 'Rs 40,000,000',
            'Plus code'              => 'XHRQ+55H Grand Baie',
            'Area'                   => 'Behind Super U, Grand Baie',
            'Listing type'           => 'Residential plot',
        ],
    ],
    [
        'title'             => '22 Perch Grand Baie',
        'property_type'     => 'Plot',
        'listing_purpose'   => 'Sale',
        'status'            => 'Available',
        'price'             => 'Rs 11,000,000',
        'price_note'        => 'Per plot',
        'size'              => '22 Perch',
        'location_name'     => 'Grand Baie',
        'location_area'     => 'Grand Baie',
        'short_description' => 'Two residential plots of 22 perches each remain available on Chemin 20 Pieds in Grand Baie.',
        'full_description'  => "These residential plots are located on Chemin 20 Pieds in Grand Baie. Each plot measures 22 perches and is priced at Rs 11,000,000.\n\nLots 1 and 2 in the scheme have already sold. Lot 3 and Lot 4 remain available and can be purchased separately, making this a straightforward option for buyers who want a defined plot size in a familiar Grand Baie address.\n\nThe location sits close to daily amenities, beach access, and the wider lifestyle appeal that draws buyers to the north coast year round.",
        'is_featured'       => 1,
        'show_on_home'      => 1,
        'latitude'          => '-20.0072594',
        'longitude'         => '57.6002083',
        'google_maps_link'  => 'https://maps.app.goo.gl/X4MsUTYrWCERQyGL7',
        'features'          => [
            'Plot size'              => '22 perches each',
            'Price'                  => 'Rs 11,000,000 per plot',
            'Plus code'              => 'XJV2+33W Grand Baie',
            'Available lots'         => 'Lot 3 and Lot 4',
            'Sold lots'              => 'Lot 1 and Lot 2',
            'Road'                   => 'Chemin 20 Pieds, Grand Baie',
        ],
    ],
];
